### PR TITLE
Add Sourcehawk Scan to CI

### PR DESCRIPTION
**Pull request by brianwyka**
Sourcehawk scan will run on pushes to `master` and on pull requests

### CODE REVIEW

**Review by pkn4645 — COMMENTED** [review]
do we need to rename our `master` branch to `main` in order for this to work properly? @brianwyka @woodrbe

**Comment by brianwyka** [comment]
Nice catch @pkn4645 .  I'll update the config here.

**Comment by brianwyka** [comment]
Scan passed!
https://github.com/Optum/optum.github.io/pull/29/checks?check_run_id=1354054190

**Review by pkn4645 — APPROVED** [review]
looks cool 👍

**Pull request merged**
